manual: runlatex clean

runlatex:
	pdflatex OmegaDeveloperManual.tex
#	makeindex OmegaDeveloperManual
	pdflatex OmegaDeveloperManual.tex
	pdflatex OmegaDeveloperManual.tex

clean:
	rm -fv OmegaDeveloperManual.aux OmegaDeveloperManual.idx OmegaDeveloperManual.ilg OmegaDeveloperManual.ind OmegaDeveloperManual.log OmegaDeveloperManual.out OmegaDeveloperManual.toc
